# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
#  Examples:
#  type 1 history, type 2 temple, type 3 nature
#  cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#  Mayor.create(name: 'Emanuel', city: cities.first)


Location.create(location_type: 1, ch_name: "富貴角燈塔", en_name: "Fugui Cape Lighthouse", lat: "25.2983581", lng: "121.5380556", description: "Fugui Cape Lighthouse is the northernmost landmark on Taiwan Island. It was built in 1897 and stands at 14.3 meters high. All the building materials were shipped from Japan and its black-and-white exterior is very eye-catching, so much so you can see it from miles away! As a functioning lighthouse, the tower is equipped with a foghorn that guides the sailors home when it gets misty at sea. The inside of the lighthouse is not currently open for visitors, but you can stand on the trail looking out at the beautiful Laomei Bay and the amazing geological features in the surrounding.")
Location.create(location_type: 2, ch_name: "法鼓山", en_name: "Dharma Drum Mountain", lat: "25.2395184", lng: "121.6152937", description: "In the Dharma Drum Mountain, the colors of buildings consist mostly of brown, gray and white, praising for bounty of earth and reflecting the solemnity and equanimity of Buddhism. There are three pilgrimage routes up in the mountain: Xibing Trail, Qiyuan Trail, and Chaoshan path. Along the Xibing Trail, there are spots for people to practice meditation. The site is surrounded by two streams and the quiet and beautiful scenery can stabilize a cluttered mind. The site regularly organizes meditation activities to help wash away the stresses and worries of the secular world.")
Location.create(location_type: 3, ch_name: "野柳", en_name: "Yehliu", lat: "25.2048994", lng: "121.6894531", description: "Yehliu is a cape of about 1,700 meters long formed by Datun Mountain reaching into the sea. When overlooked from above, the place is like a giant turtle submerging into the sea. Thus, it is also called \"Yehliu Turtle\". Because the rock layer of seashore contains sandstone of limestone texture and it is subject to sea erosion, weathering and earth movements, there is particular scenery consisting of sea trenches/holes, candle shaped rocks, and pot shaped rocks. The place is divided into three sections. The first section has rocks like Queen's Head, Fairy's Shoe and Candle. The second section has rocks like Bean Curd, Dragon Head. The third section has sea-eroded caves, seal shaped rock, etc. The place is suitable for geological study and field research. In addition, there is a statue of Lin Tien Jane in commemoration of the person's bravery of scarifying own live for saving others. The monument describes in details the touching story. There is a marine world in Yehliu. The marine world is the first marine center in the country for exhibition of ocean evolution. It has the best sightseeing tunnel under sea, showing about 200 rare fish species and marine lives. The area of marine live specimen demonstrates many specimens of precious marine mammals and fish. It is very educational. There are excellent shows of whales, dolphins and seals, such as diving, ballet on water and other talent shows. There is a stadium with 3,500 seats.")
Location.create(location_type: 1, ch_name: "滬尾砲臺", en_name: "Hobe Fort", lat: "25.17926", lng: "121.43028", description: "The Hobe Fort was the first line of defense in Northern Taiwan during the Qing Dynasty. Although the fort was never involved in any battle, there was a battle between China and France in 1884 before the fort was built. The outer walls of the fort used to be the dorm and storage area for the soldiers.")
Location.create(location_type: 2, ch_name: "武聖廟", en_name: "Wusheng Temple", lat: "25.03362", lng: "121.45075", description: "Located at Xinzhuang Road and been built for240 years, Wusheng Temple is called Guandi Temple. It is the naional third grade historic site. Worshipping Guan Yu, Wusheng Temple is the oldest and largest temple in northern Taiwan and shares the itle of \"Top Three Temple\" with Ciyou Temple and Guangfu Temple.")
Location.create(location_type: 3, ch_name: "大尖山風景區", en_name: "Dajian Mountain", lat: "25.06666", lng: "121.66666", description: "The 460-meter-high Dajian Mountain is often considered the back garden of Xizhi. As the seasons change so does Dajian, with cherry blossoms in the beginning of spring, fireflies lighting the skies in summer, and maple leafs coloring the mountain red at the end of fall.")
Location.create(location_type: 1, ch_name: "小白宮(前清淡水關稅務司官邸)", en_name: "The Little White House", lat: "25.17409", lng: "121.43622", description: "The Little White House used to be Tamsui’s Custom Inspector General’s residence in the Qing Dynasty. In 1862, as the port became prosperous and more foreigners were stationed here, more residences were built for foreign officials. The Little White House is an impressive piece of colonial architecture. The main building is a square structure in with Spanish style halls and 11 half arches.")
Location.create(location_type: 2, ch_name: "十八王公廟", en_name: "Temple of Eighteen Deities (Shi Ba Wang Gong)", lat: "25.26861", lng: "121.57138", description: "This temple, which is notable for its bronze statue of a dog, has an interesting legend associated with it. It is said that sometime during the middle of the Qing Dynasty (1644-1911), 17 merchants and a dog died during a rough crossing from mainland China. The dog, which had tried to save its master, was buried together with the merchants, and their grave became a shrine called 18 Kings Temple.")
Location.create(location_type: 3, ch_name: "鳶山", en_name: "Yuan Mountain", lat: "24.93333", lng: "121.36666", description: "Looking out from Sanxia Old Street, one notices a mountain that looks kind of a like a kite, the hawk-like bird of prey. This is Yuan Mountain, which is also known as Vulture Mountain, one of Taiwan’s “100 Little Peaks.”")

