# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)


Location.create(location_type: 1, ch_name: "富貴角燈塔", en_name: "Fugui Cape Lighthouse", lat: "25.2983581", lng: "121.5380556", description: "Fugui Cape Lighthouse is the northernmost landmark on Taiwan Island. It was built in 1897 and stands at 14.3 meters high. All the building materials were shipped from Japan and its black-and-white exterior is very eye-catching, so much so you can see it from miles away! As a functioning lighthouse, the tower is equipped with a foghorn that guides the sailors home when it gets misty at sea. The inside of the lighthouse is not currently open for visitors, but you can stand on the trail looking out at the beautiful Laomei Bay and the amazing geological features in the surrounding.")
Location.create(location_type: 2, ch_name: "法鼓山", en_name: "Dharma Drum Mountain", lat: "25.2395184", lng: "121.6152937", description: "In the Dharma Drum Mountain, the colors of buildings consist mostly of brown, gray and white, praising for bounty of earth and reflecting the solemnity and equanimity of Buddhism. There are three pilgrimage routes up in the mountain: Xibing Trail, Qiyuan Trail, and Chaoshan path. Along the Xibing Trail, there are spots for people to practice meditation. The site is surrounded by two streams and the quiet and beautiful scenery can stabilize a cluttered mind. The site regularly organizes meditation activities to help wash away the stresses and worries of the secular world.")
Location.create(location_type: 3, ch_name: "野柳", en_name: "Yehliu", lat: "25.2048994", lng: "121.6894531", description: "Yehliu is a cape of about 1,700 meters long formed by Datun Mountain reaching into the sea. When overlooked from above, the place is like a giant turtle submerging into the sea. Thus, it is also called \"Yehliu Turtle\". Because the rock layer of seashore contains sandstone of limestone texture and it is subject to sea erosion, weathering and earth movements, there is particular scenery consisting of sea trenches/holes, candle shaped rocks, and pot shaped rocks. The place is divided into three sections. The first section has rocks like Queen's Head, Fairy's Shoe and Candle. The second section has rocks like Bean Curd, Dragon Head. The third section has sea-eroded caves, seal shaped rock, etc. The place is suitable for geological study and field research. In addition, there is a statue of Lin Tien Jane in commemoration of the person's bravery of scarifying own live for saving others. The monument describes in details the touching story. There is a marine world in Yehliu. The marine world is the first marine center in the country for exhibition of ocean evolution. It has the best sightseeing tunnel under sea, showing about 200 rare fish species and marine lives. The area of marine live specimen demonstrates many specimens of precious marine mammals and fish. It is very educational. There are excellent shows of whales, dolphins and seals, such as diving, ballet on water and other talent shows. There is a stadium with 3,500 seats.")
